// GENERATED BY mnci. Every `mnci upgrade` overwrites this file.
//
// Do not edit it: put your own blocks in eslint.config.mjs next to it, which
// imports this one and which mnci never touches once it exists.
import mnci from '@mnci/eslint-config'

// WHAT IS IN HERE. Each line is one config block, by the `name` it carries.
//
//   mnci/ignores                  paths never linted (dist, coverage, .venv, …)
//   mnci/base                     JS/TS correctness — @eslint/js, eslint-plugin-unicorn,
//                                 -promise, -n, -unused-imports
//   typescript-eslint/*           typescript-eslint's own recommended blocks
//   mnci/typescript*              TS rules on top of them, no type information needed
//   mnci/type-aware*              the rules that DO read types (no-floating-promises and
//                                 friends), scoped to {apps,libs,packages}/*/src
//   mnci/import-graph             import cycles — eslint-plugin-import-x
//   mnci/react                    JSX/TSX — @eslint-react/eslint-plugin,
//                                 eslint-plugin-react-hooks, -react-refresh, -jsx-a11y
//   mnci/regexp*                  regex correctness — eslint-plugin-regexp
//   mnci/json  mnci/jsonc  mnci/json5
//                                 eslint-plugin-jsonc — comments are allowed in .jsonc
//                                 and tsconfig.json, forbidden in plain .json
//   mnci/yaml*                    eslint-plugin-yml — your CI pipeline files
//   mnci/toml/base*               eslint-plugin-toml, PARSER ONLY: a malformed
//                                 pyproject.toml is a syntax error, nothing is styled
//   mnci/markdown                 @eslint/markdown
//   mnci/css                      @eslint/css
//   mnci/html                     @html-eslint/eslint-plugin
//   mnci/tests                    *.spec/*.test relaxations — eslint-plugin-jest
//                                 (Vitest's globals too; the two stacks share them)
//   mnci/nx-dependency-checks     @nx/eslint-plugin, on publishable packages' manifests
//   mnci/standard                 JavaScript Standard Style as ESLint rules — the
//                                 whole formatting opinion, a faithful port of
//                                 neostandard
//   mnci/house-style              the deliberate departures from Standard:
//                                 trailing commas, aligned object values,
//                                 consistent-as-needed quote-props, a blank line
//                                 before return. Composed LAST, on purpose:
//                                 nothing may follow that disables it.
//
// To list them as ESLint actually resolves them:  npx eslint --inspect-config
//
// FORMATTING IS LINTING HERE. There is no Prettier, no oxfmt and no
// `format:check` — `npm run lint` reports indentation, quotes and spacing as
// ordinary errors, and `npm run format` is `eslint . --fix`. So do not add a
// formatter: whichever one you pick will disagree with the `mnci/standard`
// block above, and because a formatter runs on save it wins silently, leaving
// `lint` to fail on files you never edited by hand.
//
// That also applies to the editor. Installing a Prettier or oxfmt extension is
// enough on its own — neither needs a config file, and with none present they
// format against their own defaults (semicolons, double quotes), which is the
// inverse of Standard.
//
// Exported as a FUNCTION, not as the resolved array. @mnci/eslint-config takes
// options — `verticalSlices` is the one a workspace is most likely to want —
// and an already-resolved array has nowhere to receive them. Calling it from
// eslint.config.mjs is what keeps every option reachable from the file you own.
//
// `workspaceRoot` is resolved HERE because both files sit at the root, and it
// is what enables the @nx/dependency-checks block.
//
// A named function declaration, exported inline. Both shapes matter and both
// are enforced by this very config: `unicorn/no-anonymous-default-export`
// rejects an anonymous arrow, and `unicorn/default-export-style` rejects
// declaring one above the export and referring to it. Either mistake fails a
// generated workspace's own lint on its first run.
export default function mnciConfig (options = {}) {
  return mnci({ workspaceRoot: import.meta.dirname, ...options })
}
