/** What changed on a page and whether it was supposed to: changed pixels grouped into reportable regions. */

export { annotateOverlay, EXPECTED_MARGIN, IDENTIFIED, MISSING, NOT_IDENTIFIED, REFERENCE, UNEXPECTED, UNSETTLED } from './annotate-overlay.algorithm'
export { composePanels } from './side-by-side.algorithm'
export type { Panel, SideAnnotations } from './side-by-side.algorithm'
export type { Annotation, Rgba } from './annotate-overlay.algorithm'
export { connectedComponents, labelComponents } from './connected-components.algorithm'
export { inkWithin, probeInk } from './probe-ink.algorithm'
export type { Component, LabelledComponents, LabelOptions } from './connected-components.algorithm'
export { DEFAULT_MIN_CHANGE_AREA, DEFAULT_MIN_MISSING_AREA, diffPage, diffPages } from './diff-pages.use-case'
export { mergeBoxes } from './merge-boxes.algorithm'
export type { MergedBox } from './merge-boxes.algorithm'
export type { Change, ComparedPage, CoordinateUnits, DiffOptions, ExpectedChange, ExpectedResult, InkProbe, PageDiff, ProbeRect, RegionInkMetrics } from './page-diff.contract'
export { measureRegionInk } from './region-ink.algorithm'
export type { RegionInk, RegionInkOptions } from './region-ink.algorithm'
export { composeSideBySide } from './side-by-side.algorithm'
