"""scanmate-ink: the numeric core, ported from @scanmate/ink.

A parallel port, not a rewrite. The TypeScript remains the reference, and every
subfeature here is measured against goldens produced by running the real
TypeScript build - see ``tools/parity``.
"""

from .content_geometry import (
    ContentExtent,
    SkewOptions,
    content_extent,
    estimate_skew,
    profile_sharpness,
)
from .deterministic_sampling import create_random, gaussian
from .frequency_analysis import fft1d, fft2d, is_power_of_two, next_power_of_two
from .geometric_transform import (
    Downscaled,
    Interpolation,
    WarpOptions,
    box_blur_raster,
    downscale_gray,
    resize_gray,
    sample_gray_bilinear,
    warp_gray,
    warp_raster,
)
from .ink_separation import (
    InkOptions,
    binarize,
    box_blur,
    coverage,
    dilate,
    gray_to_raster,
    ink_map,
    integral_image,
    otsu_threshold,
    to_grayscale,
)
from .plane_geometry import (
    IDENTITY,
    Matrix3,
    Point,
    PointMatch,
    TransformModel,
    TransformSummary,
    apply_point,
    decompose,
    invert,
    is_plausible,
    multiply,
    normalize,
    similarity,
    solve,
)
from .raster_codec import (
    BinaryImage,
    GrayImage,
    Raster,
    clone_raster,
    count_pages,
    create_binary,
    create_gray,
    create_raster,
    decode_image,
    encode_image,
    is_raster,
    read_image_metadata,
)
from .similarity_scoring import correlation, intersection_over_union, mean

__all__ = [
    "IDENTITY",
    "BinaryImage",
    "ContentExtent",
    "Downscaled",
    "InkOptions",
    "Interpolation",
    "GrayImage",
    "Raster",
    "WarpOptions",
    "binarize",
    "box_blur",
    "box_blur_raster",
    "clone_raster",
    "content_extent",
    "correlation",
    "count_pages",
    "coverage",
    "create_binary",
    "create_gray",
    "create_raster",
    "create_random",
    "decode_image",
    "dilate",
    "downscale_gray",
    "fft1d",
    "fft2d",
    "encode_image",
    "estimate_skew",
    "Matrix3",
    "Point",
    "SkewOptions",
    "PointMatch",
    "TransformModel",
    "TransformSummary",
    "apply_point",
    "decompose",
    "gaussian",
    "gray_to_raster",
    "ink_map",
    "integral_image",
    "invert",
    "is_plausible",
    "is_power_of_two",
    "intersection_over_union",
    "is_raster",
    "mean",
    "multiply",
    "next_power_of_two",
    "normalize",
    "profile_sharpness",
    "otsu_threshold",
    "similarity",
    "read_image_metadata",
    "resize_gray",
    "sample_gray_bilinear",
    "solve",
    "to_grayscale",
    "warp_gray",
    "warp_raster",
]
