"""Whether a printed figure is still the figure that was printed."""

from .glyph_cells_algorithm import (
    CONTRAST,
    JOIN,
    CellOptions,
    glyph_cells,
    glyph_words,
    place_glyphs,
    printed_characters,
)
from .glyph_templates_algorithm import (
    PER_CHARACTER,
    Templates,
    TemplateStore,
    collect_into,
    collect_templates,
    cut,
    template_key,
)
from .print_polarity_policy import PrintPolarity, print_polarity
from .verify_print_use_case import (
    FIGURE_CHARACTERS,
    MATCH_HEIGHT,
    MAX_PRINTED_SCORE,
    MIN_MARGIN,
    MIN_PRINTED_SCORE,
    MIN_RIVALS,
    MIN_SCORE,
    MIN_TEXT_RIVALS,
    TEXT_CHARACTERS,
    CellVerification,
    PrintAbstention,
    PrintCheck,
    VerifyOptions,
    verify_printed_run,
)

__all__ = [
    "CONTRAST",
    "FIGURE_CHARACTERS",
    "JOIN",
    "MATCH_HEIGHT",
    "MAX_PRINTED_SCORE",
    "MIN_MARGIN",
    "MIN_PRINTED_SCORE",
    "MIN_RIVALS",
    "MIN_SCORE",
    "MIN_TEXT_RIVALS",
    "PER_CHARACTER",
    "TEXT_CHARACTERS",
    "CellOptions",
    "CellVerification",
    "PrintAbstention",
    "PrintCheck",
    "PrintPolarity",
    "TemplateStore",
    "Templates",
    "VerifyOptions",
    "collect_into",
    "collect_templates",
    "cut",
    "glyph_cells",
    "glyph_words",
    "place_glyphs",
    "print_polarity",
    "printed_characters",
    "template_key",
    "verify_printed_run",
]
