export { glyphCells, glyphWords, placeGlyphs } from './glyph-cells.use-case'
export type { CellOptions } from './glyph-cells.use-case'
export { collectInto, collectTemplates, templateKey } from './glyph-templates.use-case'
export type { TemplateStore, Templates } from './glyph-templates.use-case'
export { mergeVerifiedFigures } from './merge-reading.mapper'
export { printPolarity } from './print-polarity.policy'
export type { PrintPolarity } from './print-polarity.policy'
export { FIGURE_CHARACTERS, TEXT_CHARACTERS, verifyPrintedRun } from './verify-print.use-case'
export type { PrintAbstention, PrintCheck } from './verify-print.use-case'
export type { PrintVerification, VerifyOptions } from './verify-print.use-case'
